version: '3.8'
services:
  database:
    image: postgres:13
    container_name: postgres_graphql
    restart: always
    environment:
      POSTGRES_PASSWORD: graph
      POSTGRES_USER: graph
      POSTGRES_DB: mutation_db
    ports:
      - 5440:5432
    volumes:
      - ./data/postgres:/var/lib/postgres
